### ISSUE TITLE
Contactar contigo

### ISSUE THREAD

**Issue by Bellothornus2** [noviluni/noviluni#1]
Hola buenos días @noviluni diste una presentación de tu trabajo como funciona y eso en el colegio CIFP Borja Moll, pues yo soy Damián, aquel chico que te habló justo despues de la presentación dandote preguntas de si la empresa podía acoger "Juniors" en Scraping u otra cosa en general, me podrías pasar tu correo electrónico o el correo del responsable con el que tengo que hablar para poder solicitar una plaza por favor?

**Comment by noviluni** [comment]
Hola @Bellothornus2!

Actualmente están buscando gente, y puedes aplicar directamente en esta oferta: https://apply.workable.com/scrapinghub/j/82B921A4F7/ . Verás que tienes algunas secciones para poner tus dudas si las tienes, y puedes plantear el tema de la Dual. Eso sí, piensa a explicarlo bien (número de horas, duración, etc.) y a hacerlo en inglés.

También puedes contactar con Jessica a través de Linkedin: https://www.linkedin.com/in/jessicalouisequinn/ . Ella es la persona encargada de la parte de contratación y le puedes preguntar lo que quieras (también en inglés). :slightly_smiling_face: 

Un saludo!

**Comment by Bellothornus2** [comment]
Okey, gracias!

Contactaré antes con Jessica Quinn ya le he enviado una petición de
contacto y le envié mi propuesta de Dual, solo queda que me conteste y eso
.
Es más, espero que no te importe, pero le dije que si tu podrías ser mi
mentor (ya que hablamos el mismo idioma y vivimos en la misma región) ya
que en el Dual debo tener sí o sí un Tutor/Mentor.
Espero que quieran a alguien que todavía está aprendiendo y eso, y que
tengo algo de experiencia, pero si me piden ya de base algo avanzado... no
sé si daré la talla.

Pero eso, te aviso si hay alguna noticia mas de esto. un saludo!

Missatge de Marc Hernández <notifications@github.com> del dia dl., 16 de
nov. 2020 a les 15:07:

**Comment by Bellothornus2** [comment]
No hace falta he intentado contactar con ella y me ha rechazado la
petición, el puesto de trabajo es para gente que ya tiene el título de
Senior, yo no pinto nada, porque ninguna empresa quiere a formar a un
Junior, pero gracias por perder el tiempo conmigo.

Missatge de Damian Ivanov Kotchev <divanov@cifpfbmoll.eu> del dia dl., 16
de nov. 2020 a les 16:04:

**Comment by noviluni** [comment]
![image](https://user-images.githubusercontent.com/22377678/99667262-6e485200-2a6c-11eb-9dfb-67aa41a83143.png)

O lo que es lo mismo: "tened iniciativa y no os rindáis".

Hay muchísimas empresas dispuestas a contratar a gente Junior, de eso no hay duda, pero piensa que nadie te debe nada. 

Scrapinghub es una empresa donde todo el mundo trabaja en remoto, lo que significa que para entrar a trabajar tienes que "competir" con mucha gente muy buena de todo el mundo. Claro que contratan a Juniors, Mid y Seniors, pero sólo a los mejores.

Debes ponerte en el otro lado y preguntarte: ¿Por qué una empresa debería contratarte a mi y no a otra persona?

Y piensa que además de la experiencia laboral hay otras cosas muy valoradas como:

* Proyectos propios --> ¿has hecho algo por tu cuenta que merezca la pena?
* Contribuciones a proyectos de otros --> ¿has aportado a proyectos Open Source?
* Trabajos / estudios / publicaciones
* Buenos perfiles en Linkedin, Github...
* Blog personal
* ...

El primer trabajo suele ser el más difícil, pero también de los que más se aprende. Trabaja este año para destacar entre los demás, haz proyectos propios, mejora tu inglés, mejora tus perfiles online... y verás que al final del camino lograrás un buen resultado.
